 version: 2
 jobs:
 >       build:
 >       >       docker:
 >       >       >       - image: circleci/golang:1.9
 >       >       working_directory: /go/src/github.com/Around
 >       >       steps:
 >       >       >       - checkout
 >       >       >       - setup_remote_docker
 >       >       >       - run: |
 >       >       >       >       docker build -t zonda114/around
 >       >       >       >       docker login -u="$zonda114" -p="$Car235934$"
 >       >       >       >       docker push zonda114/around
